# Generated by Django 5.1.1 on 2024-10-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegister',
        ),
    ]
