# Generated by Django 5.1.1 on 2025-03-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='game_id',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='gamehistory',
            name='player1Score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamehistory',
            name='player2Score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
