# Generated by Django 5.1.1 on 2025-03-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchhistory',
            name='game_id',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
