# Generated by Django 5.1.1 on 2025-03-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_history', '0002_alter_matchhistory_game_id_alter_matchhistory_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchhistory',
            name='game_id',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='winner',
            field=models.CharField(),
        ),
    ]
