# Generated by Django 5.1.1 on 2025-03-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='chat',
            field=models.ManyToManyField(to='lobby.lobbychatmessage'),
        ),
    ]
