# Generated by Django 5.1.1 on 2024-11-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='users',
            field=models.JSONField(),
        ),
    ]
