# Generated by Django 5.1.1 on 2025-01-08 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0003_message_lobby_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator('[!+?,./\\%&$]', inverse_match=True)]),
        ),
    ]
