# Generated by Django 5.1.1 on 2025-01-08 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0004_alter_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='lobby_id',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator('[+-/%!?,.$%#&*]', inverse_match=True)]),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
