# Generated by Django 5.1.1 on 2024-12-06 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0004_alter_lobby_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('z', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='lobby',
            name='gameState',
            field=models.CharField(choices=[('running', 'Running'), ('closed', 'Closed'), ('paused', 'Paused')], default='closed'),
        ),
        migrations.AddField(
            model_name='lobby',
            name='player1Score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lobby',
            name='player2Score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lobby',
            name='ballPosition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BallPosition', to='lobby.position'),
        ),
        migrations.AddField(
            model_name='lobby',
            name='paddle1Position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Paddle1Position', to='lobby.position'),
        ),
        migrations.AddField(
            model_name='lobby',
            name='paddle2Position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Paddle2Position', to='lobby.position'),
        ),
    ]
