# Generated by Django 5.1.1 on 2025-01-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0005_alter_lobby_lobby_id_alter_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='lobby_id',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
