# Generated by Django 5.1.1 on 2024-12-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0005_position_lobby_gamestate_lobby_player1score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='y',
        ),
    ]
