# Generated by Django 5.1.1 on 2024-12-06 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0006_remove_position_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='ballPosition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='BallPosition', to='lobby.position'),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='paddle1Position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Paddle1Position', to='lobby.position'),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='paddle2Position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Paddle2Position', to='lobby.position'),
        ),
    ]
