# Generated by Django 5.1.1 on 2024-12-09 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0007_alter_lobby_ballposition_alter_lobby_paddle1position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='ballPosition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BallPosition', to='lobby.position'),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='paddle1Position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Paddle1Position', to='lobby.position'),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='paddle2Position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Paddle2Position', to='lobby.position'),
        ),
    ]
