# Generated by Django 5.1.1 on 2024-12-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0009_alter_lobby_ballposition_alter_lobby_paddle1position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='player1Ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lobby',
            name='player2Ready',
            field=models.BooleanField(default=False),
        ),
    ]
