# Generated by Django 5.1.1 on 2025-01-14 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0006_alter_lobby_lobby_id'),
        ('tournament', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TournamentWinner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='lobbies',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_id',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='lobbies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TournamentGame', to='lobby.lobby'),
        ),
    ]
