# Generated by Django 5.1.1 on 2025-02-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentplayer',
            unique_together=set(),
        ),
    ]
