# Generated by Django 5.1.1 on 2025-03-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_remove_tournament_player_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='chat',
            field=models.ManyToManyField(to='tournament.tmessage'),
        ),
    ]
