# Generated by Django 5.1.1 on 2025-02-10 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0007_lobby_winner'),
        ('tournament', '0002_alter_tournamentplayer_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='lobbies',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='winner',
        ),
        migrations.AddField(
            model_name='tournament',
            name='game1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Semifinal1', to='lobby.lobby'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='game2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Semifinal2', to='lobby.lobby'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='game3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Final', to='lobby.lobby'),
        ),
    ]
