# Generated by Django 5.1.1 on 2025-03-09 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tmessage_tournament_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmessage',
            name='color',
        ),
    ]
