# Generated by Django 5.1.1 on 2025-02-12 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0007_lobby_winner'),
        ('tournament', '0004_alter_tournament_game1_alter_tournament_game2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='game1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='g1', to='lobby.lobby'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='g2', to='lobby.lobby'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='g3', to='lobby.lobby'),
        ),
    ]
