# Generated by Django 5.1.1 on 2025-03-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_remove_tmessage_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmessage',
            name='color',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
