# Generated by Django 5.1.1 on 2025-02-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_alter_tournament_game1_alter_tournament_game2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='inGame',
            field=models.BooleanField(default=False),
        ),
    ]
