# Generated by Django 5.1.1 on 2025-03-10 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0002_alter_lobby_chat'),
        ('tournament', '0005_tmessage_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='game1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='g1', to='lobby.lobby'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='g2', to='lobby.lobby'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='g3', to='lobby.lobby'),
        ),
    ]
