# Generated by Django 5.1.1 on 2025-03-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_alter_tournament_game1_alter_tournament_game2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='winner1',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner3',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
