# Generated by Django 5.1.1 on 2025-02-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_tournamentplayer_is_returning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='game3',
        ),
    ]
