# Generated by Django 5.1.1 on 2025-03-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_tournament_winner1_tournament_winner2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmessage',
            name='color',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
