# Generated by Django 5.1.1 on 2025-02-26 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0007_lobby_winner'),
        ('tournament', '0008_alter_tournamentplayer_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='game1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='g1', to='lobby.lobby'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='g2', to='lobby.lobby'),
        ),
    ]
