# Generated by Django 5.1.1 on 2025-03-01 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0007_lobby_winner'),
        ('tournament', '0009_alter_tournament_game1_alter_tournament_game2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='game3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='g3', to='lobby.lobby'),
        ),
    ]
