# Generated by Django 5.1.1 on 2025-03-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_alter_tournament_game1_alter_tournament_game2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
