# Generated by Django 5.1.1 on 2025-03-03 12:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_tournamentplayer_is_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='player_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25), blank=True, null=True, size=4),
        ),
    ]
