# Generated by Django 5.1.1 on 2024-12-03 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxylobby',
            options={'managed': False, 'verbose_name': 'Lobby', 'verbose_name_plural': 'Lobbies'},
        ),
    ]
