# Generated by Django 5.1.1 on 2025-03-11 00:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1908, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2025, 3, 11))]),
        ),
    ]
