# Generated by Django 5.1.1 on 2024-11-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_friendships_created_alter_friendships_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendships',
        ),
    ]
