# Generated by Django 5.1.1 on 2024-12-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_delete_friendships'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp_secret',
            field=models.TextField(blank=True, null=True),
        ),
    ]
