# Generated by Django 5.1.1 on 2025-01-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_profile_email_profile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
