# Generated by Django 5.1.1 on 2024-11-22 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_friendships_created_alter_friendships_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendships',
            options={'verbose_name': 'Friendship', 'verbose_name_plural': 'Friendships'},
        ),
        migrations.AlterField(
            model_name='friendships',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
