# Generated by Django 5.1.1 on 2025-01-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
    ]
