# Generated by Django 5.1.1 on 2024-11-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_profile_test_profile_test2_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='test',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='test2',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default={}),
        ),
    ]
